spring:
  profiles:
    active: dev

---
spring:
  profile: dev
  application:
    name: config-server-test-eureka

server:
  port: 3434

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: eureka

  client:
    serviceUrl:
      defaultZone: http://127.0.0.1/eureka
