spring:
  profiles:
    active: test

---
spring:
  profiles: dev
  application:
    name: test-spring-cloud-config-dev
server:
  port:12345

    
---
spring:
  profiles: test
  application:
    name: test-spring-cloud-config-test
server:
  port: 54321
